# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OPGG-iOS-mobile-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OPGG-iOS-mobile-test
  pod 'Alamofire'
  pod 'Kingfisher', '~> 6.3.1'
end
